# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[package]
disabled = true

# disables multiline prompt
[line_break]
disabled = true

[aws]

[rust]
detect_files = ["cargo.toml"]
